# Generated by Django 5.2.17 on 2026-08-27 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerrouImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=20, unique=True, verbose_name='clé')),
                ('pris_le', models.DateTimeField(auto_now_add=True, verbose_name='pris le')),
                ('motif', models.CharField(blank=True, max_length=60, verbose_name='motif')),
                ('lot', models.UUIDField(blank=True, null=True, verbose_name='lot')),
            ],
            options={
                'verbose_name': "verrou d'import",
                'verbose_name_plural': "verrous d'import",
            },
        ),
        migrations.CreateModel(
            name='ImportPresences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('fichier', 'Fichier'), ('endpoint', 'Endpoint')], max_length=10, verbose_name='source')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('reussi', 'Réussi'), ('echec', 'Échec')], db_index=True, max_length=10, verbose_name='statut')),
                ('lot', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='lot')),
                ('mois', models.CharField(blank=True, max_length=7, verbose_name='mois')),
                ('debut', models.DateField(blank=True, null=True, verbose_name='début de fenêtre')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='fin de fenêtre')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='payload')),
                ('forme', models.CharField(blank=True, max_length=20, verbose_name='forme reçue')),
                ('empreinte', models.CharField(blank=True, max_length=64, verbose_name='empreinte SHA-256')),
                ('taille', models.PositiveIntegerField(default=0, verbose_name='taille reçue (octets)')),
                ('message', models.TextField(blank=True, verbose_name='message du payload')),
                ('invariant_ok', models.BooleanField(blank=True, null=True, verbose_name='invariant vérifié')),
                ('nb_jours', models.PositiveIntegerField(default=0, verbose_name='nombre de jours')),
                ('nb_lignes', models.PositiveIntegerField(default=0, verbose_name='nombre de lignes')),
                ('nb_presents', models.PositiveIntegerField(default=0, verbose_name='nombre de présents')),
                ('erreur', models.CharField(blank=True, max_length=200, verbose_name='erreur')),
                ('nom_fichier', models.CharField(blank=True, max_length=120, verbose_name='nom du fichier')),
                ('importe_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='importé le')),
                ('termine_le', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
                ('duree_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name="durée de l'appel (ms)")),
                ('webhook_envoye', models.BooleanField(default=False, verbose_name='webhook envoyé')),
                ('importe_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_presences', to=settings.AUTH_USER_MODEL, verbose_name='importé par')),
            ],
            options={
                'verbose_name': 'import de présences',
                'verbose_name_plural': 'imports de présences',
                'ordering': ['-importe_le', '-id'],
                'indexes': [models.Index(fields=['debut', 'fin'], name='presences_i_debut_749a31_idx')],
            },
        ),
    ]
