# Generated by Django 5.2.17 on 2026-09-06 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=7, verbose_name='mois')),
                ('numero', models.PositiveIntegerField(verbose_name='numéro')),
                ('state', models.JSONField(default=dict, verbose_name='état')),
                ('version_de_base', models.PositiveIntegerField(blank=True, help_text='Numéro de la version affichée quand celle-ci a été enregistrée. 0 = aucune.', null=True, verbose_name='version de base')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('verifications', models.JSONField(blank=True, default=list, verbose_name='vérifications')),
                ('publiee', models.BooleanField(default=False, verbose_name='publiée')),
                ('publie_le', models.DateTimeField(blank=True, null=True, verbose_name='publiée le')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_planning', to=settings.AUTH_USER_MODEL, verbose_name='enregistrée par')),
                ('publie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_planning_publiees', to=settings.AUTH_USER_MODEL, verbose_name='publiée par')),
            ],
            options={
                'verbose_name': 'version du planning',
                'verbose_name_plural': 'versions du planning',
                'ordering': ('mois', '-numero'),
                'constraints': [models.UniqueConstraint(fields=('mois', 'numero'), name='planningversion_mois_numero_unique')],
            },
        ),
    ]
