# Generated by Django 5.2.17 on 2026-09-06 22:26, puis édité (brique 4b) :
# `version_de_base` passe en NOT NULL avec le défaut 0. Le service l'a toujours
# posé (0 = aucune version de base) ; le `RunPython` est un filet, nécessaire
# AVANT l'`AlterField` sur PostgreSQL (`SET NOT NULL` refuse un NULL restant).

from django.db import migrations, models


def remplir_zero(apps, schema_editor):
    """Idempotent : les lignes sans version de base reçoivent 0."""
    PlanningVersion = apps.get_model("planning", "PlanningVersion")
    PlanningVersion.objects.filter(version_de_base__isnull=True).update(version_de_base=0)


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remplir_zero, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='planningversion',
            name='version_de_base',
            field=models.PositiveIntegerField(default=0, help_text='Numéro de la version affichée quand celle-ci a été enregistrée. 0 = aucune.', verbose_name='version de base'),
        ),
    ]
