# Generated by Django 5.2.17 on 2026-09-01 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0003_compte_email_en_attente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60, unique=True, verbose_name='libellé')),
                ('bloquant', models.BooleanField(default=True, help_text='Retire une journée au planning. Les types informatifs ne le font pas.', verbose_name='bloquant')),
                ('categorie', models.CharField(choices=[('demande', 'Soumis à décision'), ('declare', 'Déclaration (effective immédiatement)')], default='declare', max_length=10, verbose_name='catégorie')),
                ('paie', models.BooleanField(default=False, help_text='Entre dans les données transmises pour la paie.', verbose_name='compté pour la paie')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans les listes déroulantes.", verbose_name='ordre')),
            ],
            options={
                'verbose_name': "type d'absence",
                'verbose_name_plural': "types d'absence",
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceSalariee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='premier jour')),
                ('date_fin', models.DateField(verbose_name='dernier jour')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('declaree', 'Déclarée')], db_index=True, max_length=12, verbose_name='statut')),
                ('precision', models.CharField(blank=True, help_text="Facultatif. N'apparaît jamais dans le journal, les logs ni un webhook.", max_length=120, verbose_name='précision')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('decide_le', models.DateTimeField(blank=True, null=True, verbose_name='décidée le')),
                ('jours_comptes_calcules', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='jours comptés (calculés)')),
                ('jours_comptes', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='jours comptés (retenus)')),
                ('jours_retenus', models.JSONField(blank=True, default=list, help_text='Dates ISO des jours comptés. Sert à la répartition par mois.', verbose_name='jours retenus')),
                ('corrige_le', models.DateTimeField(blank=True, null=True, verbose_name='corrigée le')),
                ('a_effacer_le', models.DateField(blank=True, null=True, verbose_name='à effacer le')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_saisies', to=settings.AUTH_USER_MODEL, verbose_name='saisie par')),
                ('corrige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_corrigees', to=settings.AUTH_USER_MODEL, verbose_name='corrigée par')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_decidees', to=settings.AUTH_USER_MODEL, verbose_name='décidée par')),
                ('personne', models.ForeignKey(limit_choices_to={'role_metier__in': ('assistante', 'secretaire')}, on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='comptes.personne', verbose_name='personne')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='absences.typeabsence', verbose_name='type')),
            ],
            options={
                'verbose_name': 'absence',
                'verbose_name_plural': 'absences',
                'ordering': ['-date_debut', '-id'],
                'indexes': [models.Index(fields=['personne', 'date_debut'], name='absences_ab_personn_7caf01_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='absence_dates_ordonnees')],
            },
        ),
    ]
