# Generated by Django 5.2.17 on 2026-08-26 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quand', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='quand')),
                ('action', models.CharField(db_index=True, max_length=60, verbose_name='action')),
                ('type_objet', models.CharField(blank=True, max_length=40, verbose_name="type d'objet")),
                ('id_objet', models.CharField(blank=True, max_length=40, verbose_name="identifiant d'objet")),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='détails')),
                ('qui', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_audit', to=settings.AUTH_USER_MODEL, verbose_name='qui')),
            ],
            options={
                'verbose_name': "événement d'audit",
                'verbose_name_plural': "événements d'audit",
                'ordering': ['-quand', '-id'],
            },
        ),
    ]
