# Generated by Django 5.2.17 on 2026-08-26 20:57

import comptes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text="Renseigné à partir de la brique 2. Laisser vide pour l'instant.", max_length=30, null=True, unique=True, verbose_name='code')),
                ('nom', models.CharField(max_length=80, verbose_name='nom')),
                ('prenom', models.CharField(max_length=80, verbose_name='prénom')),
                ('role_metier', models.CharField(choices=[('assistante', 'Assistante'), ('secretaire', 'Secrétaire'), ('praticien', 'Praticien')], max_length=20, verbose_name='rôle métier')),
                ('heures_hebdo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='heures hebdomadaires')),
                ('jours_fixes', models.JSONField(blank=True, default=list, help_text='Liste de jours, par exemple ["Mardi", "Jeudi"].', verbose_name='jours fixes')),
                ('planifiee', models.BooleanField(default=False, verbose_name='planifiée')),
                ('couleur', models.CharField(blank=True, max_length=20, verbose_name='couleur')),
                ('agenda_doctolib', models.CharField(blank=True, max_length=120, verbose_name='agenda Doctolib')),
                ('email_contact', models.EmailField(blank=True, help_text="Adresse d'invitation. Distincte de l'adresse de connexion du compte.", max_length=254, verbose_name='adresse de contact')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'personne',
                'verbose_name_plural': 'personnes',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('role', models.CharField(choices=[('cabinet', 'Cabinet'), ('principale', 'Assistante principale'), ('salariee', 'Salariée')], default='salariee', max_length=20, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name="accès à l'administration")),
                ('invite_le', models.DateTimeField(blank=True, null=True, verbose_name='invité le')),
                ('active_le', models.DateTimeField(blank=True, null=True, verbose_name='activé le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('personne', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compte', to='comptes.personne', verbose_name='personne')),
            ],
            options={
                'verbose_name': 'compte',
                'verbose_name_plural': 'comptes',
                'ordering': ['email'],
            },
            managers=[
                ('objects', comptes.models.CompteManager()),
            ],
        ),
    ]
