# Generated by Django 5.2.17 on 2026-08-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='code',
            field=models.CharField(blank=True, help_text="Posé automatiquement à la création s'il est libre. À saisir à la main en cas de collision.", max_length=30, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AddConstraint(
            model_name='personne',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom'), name='personne_nom_prenom_unique'),
        ),
    ]
