# Generated by Django 5.2.17 on 2026-09-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_personne_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='email_en_attente',
            field=models.EmailField(blank=True, max_length=254, verbose_name='adresse en attente de confirmation'),
        ),
    ]
