# Generated by Django 5.2.17 on 2026-08-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteurDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=80, verbose_name='clé')),
                ('fenetre_debut', models.PositiveBigIntegerField(verbose_name='début de fenêtre')),
                ('nb', models.PositiveIntegerField(default=0, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'compteur de débit',
                'verbose_name_plural': 'compteurs de débit',
                'indexes': [models.Index(fields=['fenetre_debut'], name='socle_compt_fenetre_1327b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('cle', 'fenetre_debut'), name='compteurdebit_cle_fenetre_unique')],
            },
        ),
    ]
